[aws]
disabled = true
#format = " [$symbol$profile]($style) "
#style = "bold yellow"
#symbol = "🅰 "
#[aws.region_aliases]
#ap-southeast-2 = "au"
#us-east-1 = "va"
#ap-southeast-1 = "sg"

[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold green"

[git_commit]
disabled = true
commit_hash_length = 7
tag_symbol = "🔖 "
style = "underline green"
only_detached = false

[git_status]
disabled = false
style = "blue"
staged = '[++\($count\)](green)'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[python]
disabled = false
# format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

[gcloud]
disabled = true

[nodejs]
format = "via [🤖 $version](bold green) "
